# Generated by https://smithery.ai. See: https://smithery.ai/docs/config#dockerfile
FROM python:3.12-slim

# Set working directory
WORKDIR /app

# Install system dependencies if needed
RUN apt-get update && apt-get install -y --no-install-recommends \
    gcc \
    libpq-dev \
 && rm -rf /var/lib/apt/lists/*

# Copy project files
COPY . .

# Install pip dependencies
RUN pip install --no-cache-dir -r requirements.txt || pip install --no-cache-dir -e .

# Expose port if using HTTP transport (optional)
EXPOSE 8000

# Default command: run the server with stdio transport
CMD ["python", "src/mysql/server.py"]
